### ISSUE TITLE
URL structures with only the item or media identifier

### ISSUE THREAD

**Issue by xelatitep** [Daniel-KM/Omeka-S-module-CleanUrl#3]
Hi Daniel, thanks for that great module!

I'm wondering if there are plans to make the URL structures containing only the item or media identifier (no main path, prefix or collection identifier) available in a near future. That would certainly be appreciated.

Thanks!

**Comment by Daniel-KM** [comment]
So you want /s/my-site/my-item or /s/my-site/my-media ? Nobody asked me for that, but I think it's possible to do, even if there are some risk for conflict with standard routes (pages, etc.).

**Comment by xelatitep** [comment]
Yes, this is exactly what I'm looking for, but I would also like to hide the site slug, so the URL would be my-domain-name/omeka-folder/my-media or my-item. I'm trying to get the shortest URLs possible to access the item or media pages using the ARK identifiers.

**Comment by Daniel-KM** [comment]
For the site slug, you can remove it: see readme about the main slug.

**Comment by Daniel-KM** [comment]
Hi, This is integrated in last version (3.5.13), so you can have short url.
